Containerize Libvirt
kubevirt/libvirt pull request #1
Opened 2017-04-10 16:32 UTC by stu-gott

Provide Libvirtd inside a container. The intention is that
/var/run/libvirt will be bind mounted from the host, and optionally
Ports 16509/5900+ if TCP connections are required for libvirt or
spice/vnc.

2017-04-10 16:33 UTC, stu-gott commented
I'm conflicted on one point. I put the Dockerfile and components at the toplevel of this git repo. Is that the correct approach, or should we put them into a subfolder?

2017-04-11 07:16 UTC, rmohr requested changes
Does this also need virtlogd running somewhere?

In principle we could add a docker compose file which start libvirtd and virtlogd and run tests on travis with qemu full emulation.

2017-04-11 07:16 UTC, rmohr commented on .gitignore
> +vendor/*
You can clean up this file

2017-04-11 07:16 UTC, rmohr commented on README.md
> +      --user=root \
do we need --ipc=host too?

2017-04-11 07:16 UTC, rmohr commented on README.md
> +* The D-Bus socket is not exposed inside the container
We could actually provide an example here, on how to expose the dbus socket to the container (something like -v /host/socket:/container/socket)

2017-04-11 07:16 UTC, rmohr commented on libvirtd.sh
> +if [[ -n "$LIBVIRTD_DEFAULT_NETWORK_DEVICE" ]]; then
I am not so happy with this section but good enough for now

2017-04-21 13:04 UTC, merged